"""crea_tabelle_iniziali

Revision ID: 7f8d4d1d7212
Revises: 
Create Date: 2026-05-05 07:58:08.890264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f8d4d1d7212'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_revenue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_code', sa.String(length=3), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('rooms_sold', sa.Integer(), nullable=False),
    sa.Column('rooms_available', sa.Integer(), nullable=False),
    sa.Column('pax', sa.Integer(), nullable=False),
    sa.Column('revenue_rooms', sa.Float(), nullable=False),
    sa.Column('revenue_fnb', sa.Float(), nullable=False),
    sa.Column('revenue_extra', sa.Float(), nullable=False),
    sa.Column('revenue_total', sa.Float(), nullable=False),
    sa.Column('nome_file', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_code', 'data', name='uq_hotel_data')
    )
    op.create_index(op.f('ix_daily_revenue_data'), 'daily_revenue', ['data'], unique=False)
    op.create_index(op.f('ix_daily_revenue_hotel_code'), 'daily_revenue', ['hotel_code'], unique=False)
    op.create_index(op.f('ix_daily_revenue_id'), 'daily_revenue', ['id'], unique=False)
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('default_rooms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotels_code'), 'hotels', ['code'], unique=True)
    op.create_index(op.f('ix_hotels_id'), 'hotels', ['id'], unique=False)
    op.create_table('hotel_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('open_date', sa.Date(), nullable=False),
    sa.Column('close_date', sa.Date(), nullable=False),
    sa.Column('total_rooms', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'season_year', name='uq_hotel_stagione_anno')
    )
    op.create_index(op.f('ix_hotel_seasons_hotel_id'), 'hotel_seasons', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_hotel_seasons_id'), 'hotel_seasons', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hotel_seasons_id'), table_name='hotel_seasons')
    op.drop_index(op.f('ix_hotel_seasons_hotel_id'), table_name='hotel_seasons')
    op.drop_table('hotel_seasons')
    op.drop_index(op.f('ix_hotels_id'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_code'), table_name='hotels')
    op.drop_table('hotels')
    op.drop_index(op.f('ix_daily_revenue_id'), table_name='daily_revenue')
    op.drop_index(op.f('ix_daily_revenue_hotel_code'), table_name='daily_revenue')
    op.drop_index(op.f('ix_daily_revenue_data'), table_name='daily_revenue')
    op.drop_table('daily_revenue')
    # ### end Alembic commands ###
